"""
This type stub file was generated by pyright.
"""

import asyncio
import py_eureka_client.http_client as http_client
from typing import Callable, Dict, List, Union
from py_eureka_client.eureka_basic import Applications

"""
Copyright (c) 2018 Keijack Wu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
_logger = ...
class EurekaServerConf:
    def __init__(self, eureka_server=..., eureka_domain=..., eureka_protocol=..., eureka_basic_auth_user=..., eureka_basic_auth_password=..., eureka_context=..., eureka_availability_zones=..., region=..., zone=...) -> None:
        ...
    
    @property
    def zone(self) -> str:
        ...
    
    @property
    def servers(self) -> Dict:
        ...
    
    @property
    def servers_in_zone(self) -> List[str]:
        ...
    
    @property
    def servers_not_in_zone(self) -> List[str]:
        ...
    


class EurekaServerConnectionException(http_client.URLError):
    ...


class DiscoverException(http_client.URLError):
    ...


class NodeError:
    def __init__(self, node, error: Exception) -> None:
        ...
    


class WalkNodeException(http_client.URLError):
    def __init__(self, reason, node_errors: List[NodeError] = ...) -> None:
        ...
    


class EurekaClient:
    """
    Example:

    >>> client = EurekaClient(
            eureka_server="http://my_eureka_server_peer_1/eureka/v2,http://my_eureka_server_peer_2/eureka/v2", 
            app_name="python_module_1", 
            instance_port=9090)
    >>> client.start()
    >>> result = client.do_service("APP_NAME", "/context/path", return_type="json")

    EIPs support: 

    You can configure EIP using `eureka_availability_zones` and specify the `zone` of your instance. But please aware, that the client won't fill up the metadata atomatically, 
    You should put it to the `metadata` when creating the object.

    >>> client = EurekaClient(eureka_availability_zones={
                "us-east-1c": "http://ec2-552-627-568-165.compute-1.amazonaws.com:7001/eureka/v2/,http://ec2-368-101-182-134.compute-1.amazonaws.com:7001/eureka/v2/",
                "us-east-1d": "http://ec2-552-627-568-170.compute-1.amazonaws.com:7001/eureka/v2/",
                "us-east-1e": "http://ec2-500-179-285-592.compute-1.amazonaws.com:7001/eureka/v2/"}, 
                zone="us-east-1c",
                app_name="python_module_1",
                instance_port=9090,
                data_center_name="Amazon")

    EurekaClient supports DNS discovery feature.

    For instance, following is a DNS TXT record created in the DNS server that lists the set of available DNS names for a zone.

    >>> txt.us-east-1.mydomaintest.netflix.net="us-east-1c.mydomaintest.netflix.net" "us-east-1d.mydomaintest.netflix.net" "us-east-1e.mydomaintest.netflix.net"

    Then, you can define TXT records recursively for each zone similar to the following (if more than one hostname per zone, space delimit)

    >>> txt.us-east-1c.mydomaintest.netflix.net="ec2-552-627-568-165.compute-1.amazonaws.com" "ec2-368-101-182-134.compute-1.amazonaws.com"
    >>> txt.us-east-1d.mydomaintest.netflix.net="ec2-552-627-568-170.compute-1.amazonaws.com"
    >>> txt.us-east-1e.mydomaintest.netflix.net="ec2-500-179-285-592.compute-1.amazonaws.com"

    And then you can create the client like: 

    >>> client = EurekaClient(eureka_domain="mydomaintest.netflix.net",
                region="us-east-1",
                zone="us-east-1c",
                app_name="python_module_1", 
                instance_port=9090,
                data_center_name="Amazon")

    Eureka client also supports setting up the protocol, basic authentication and context path of your eureka server. 

    >>> client = EurekaClient(eureka_domain="mydomaintest.netflix.net",
                region="us-east-1",
                zone="us-east-1c",
                eureka_protocol="https",
                eureka_basic_auth_user="keijack",
                eureka_basic_auth_password="kjauthpass",
                eureka_context="/eureka/v2",
                app_name="python_module_1", 
                instance_port=9090,
                data_center_name="Amazon")

    or

    >>> client = EurekaClient(eureka_server="my_eureka_server_peer_1,my_eureka_server_peer_2",
                eureka_protocol="https",
                eureka_basic_auth_user="keijack",
                eureka_basic_auth_password="kjauthpass",
                eureka_context="/eureka/v2",
                app_name="python_module_1", 
                instance_port=9090)

    You can use `do_service`, `wall_nodes` to call the remote services.

    >>> res = eureka_client.do_service("OTHER-SERVICE-NAME", "/service/context/path")

    >>> def walk_using_your_own_urllib(url):
            ...

        res = await client.walk_nodes("OTHER-SERVICE-NAME", "/service/context/path", walker=walk_using_your_own_urllib)


    Attributes:

    * eureka_server: The eureka server url, if you want have deploy a cluster to do the failover, use `,` to separate the urls.

    * eureka_domain: The domain name when using the DNS discovery.

    * region: The region when using DNS discovery.

    * zone: Which zone your instances belong to, default is `default`.

    * eureka_availability_zones: The zones' url configurations.

    * eureka_protocol: The protocol of the eureka server, if the url include this part, this protocol will not add to the url.

    * eureka_basic_auth_user: User name of the basic authentication of the eureka server, if the url include this part, this protocol will not add to the url.

    * eureka_basic_auth_password: Password of the basic authentication of the eureka server, if the url include this part, this protocol will not add to the url.

    * eureka_context: The context path of the eureka server, if the url include this part, this protocol will not add to the url, default is `/eureka`
        which meets the spring-boot eureka context but not the Netflix eureka server url.

    * prefer_same_zone: When set to True, will first find the eureka server in the same zone to register, and find the instances in the same zone to do
        the service. Or it will randomly choose the eureka server  to register and instances to do the services, default is `True`.

    * should_register: When set to False, will not register this instance to the eureka server, default is `True`.

    * should_discover: When set to False, will not pull registry from the eureka server, default is `True`.

    The following parameters all the properties of this instances, all this fields will be sent to the eureka server.

    * app_name: The application name of this instance.

    * instance_id: The id of this instance, if not specified, will generate one by app_name and instance_host/instance_ip and instance_port.

    * instance_host: The host of this instance. 

    * instance_ip: The ip of this instance. If instance_host and instance_ip are not specified, will try to find the ip via connection to the eureka server.

    * instance_ip_network: The ip network of this instance. If instance_host and instance_ip are not specified, will try to find the ip from the avaiable network adapters that matches the specified network. For example 192.168.1.0/24.

    * instance_port: The port of this instance. 

    * instance_unsecure_port_enabled: Set whether enable the instance's unsecure port, default is `True`.

    * instance_secure_port: The secure port of this instance. 

    * instance_secure_port_enabled: Set whether enable the instance's secure port, default is `False`.

    * data_center_name: Accept `Netflix`, `Amazon`, `MyOwn`, default is `MyOwn`

    * renewal_interval_in_secs: Will send heartbeat and pull registry in this time interval, defalut is 30 seconds

    * duration_in_secs: Sets the client specified setting for eviction (e.g. how long to wait without renewal event).

    * home_page_url: The home page url of this instance.

    * status_page_url: The status page url of this instance.

    * health_check_url: The health check url of this instance.

    * secure_health_check_url: The secure health check url of this instance.

    * vip_adr: The virtual ip address of this instance.

    * secure_vip_addr: The secure virtual ip address of this instance.

    * is_coordinating_discovery_server: Sets a flag if this instance is the same as the discovery server that is
        return the instances. This flag is used by the discovery clients to
        identity the discovery server which is coordinating/returning the
        information.

    * metadata: The metadata map of this instances.

    * remote_regions: Will also find the services that belongs to these regions.

    * ha_strategy: Specify the strategy how to choose a instance when there are more than one instanse of an App. 

    * strict_service_error_policy: When set to True, all errors(Including connection error and HttpError, like http 
        status code is not 200) will consider as errors; Otherwise, only (ConnectionError, TimeoutError, socket.timeout) 
        will be considered as errors, and other excptions and errors will be raised to upstream. Default is True.

    """
    def __init__(self, eureka_server: str = ..., eureka_domain: str = ..., region: str = ..., zone: str = ..., eureka_availability_zones: Dict[str, str] = ..., eureka_protocol: str = ..., eureka_basic_auth_user: str = ..., eureka_basic_auth_password: str = ..., eureka_context: str = ..., prefer_same_zone: bool = ..., should_register: bool = ..., should_discover: bool = ..., on_error: Callable = ..., app_name: str = ..., instance_id: str = ..., instance_host: str = ..., instance_ip: str = ..., instance_ip_network: str = ..., instance_port: int = ..., instance_unsecure_port_enabled: bool = ..., instance_secure_port: int = ..., instance_secure_port_enabled: bool = ..., data_center_name: str = ..., renewal_interval_in_secs: int = ..., duration_in_secs: int = ..., home_page_url: str = ..., status_page_url: str = ..., health_check_url: str = ..., secure_health_check_url: str = ..., vip_adr: str = ..., secure_vip_addr: str = ..., is_coordinating_discovery_server: bool = ..., metadata: Dict = ..., remote_regions: List[str] = ..., ha_strategy: int = ..., strict_service_error_policy: bool = ...) -> None:
        ...
    
    @property
    def should_register(self) -> bool:
        ...
    
    @property
    def should_discover(self) -> bool:
        ...
    
    @property
    def zone(self) -> str:
        ...
    
    @property
    def applications(self) -> Applications:
        ...
    
    async def register(self, status: str = ..., overriddenstatus: str = ...) -> None:
        ...
    
    async def cancel(self) -> None:
        ...
    
    async def send_heartbeat(self, overridden_status: str = ...) -> None:
        ...
    
    async def status_update(self, new_status: str) -> None:
        ...
    
    async def delete_status_override(self) -> None:
        ...
    
    async def walk_nodes(self, app_name: str = ..., service: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., walker: Callable = ...) -> Union[str, Dict, http_client.HttpResponse]:
        ...
    
    async def do_service(self, app_name: str = ..., service: str = ..., return_type: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., method: str = ..., headers: Dict[str, str] = ..., data: Union[bytes, str, Dict] = ..., timeout: float = ...) -> Union[str, Dict, http_client.HttpResponse]:
        ...
    
    async def start(self) -> None:
        ...
    
    async def stop(self) -> None:
        ...
    


__cache_key = ...
__cache_clients: Dict[str, EurekaClient] = ...
__cache_clients_lock = ...
async def init_async(eureka_server: str = ..., eureka_domain: str = ..., region: str = ..., zone: str = ..., eureka_availability_zones: Dict[str, str] = ..., eureka_protocol: str = ..., eureka_basic_auth_user: str = ..., eureka_basic_auth_password: str = ..., eureka_context: str = ..., prefer_same_zone: bool = ..., should_register: bool = ..., should_discover: bool = ..., on_error: Callable = ..., app_name: str = ..., instance_id: str = ..., instance_host: str = ..., instance_ip: str = ..., instance_ip_network: str = ..., instance_port: int = ..., instance_unsecure_port_enabled: bool = ..., instance_secure_port: int = ..., instance_secure_port_enabled: bool = ..., data_center_name: str = ..., renewal_interval_in_secs: int = ..., duration_in_secs: int = ..., home_page_url: str = ..., status_page_url: str = ..., health_check_url: str = ..., secure_health_check_url: str = ..., vip_adr: str = ..., secure_vip_addr: str = ..., is_coordinating_discovery_server: bool = ..., metadata: Dict = ..., remote_regions: List[str] = ..., ha_strategy: int = ..., strict_service_error_policy: bool = ...) -> EurekaClient:
    """
    Initialize an EurekaClient object and put it to cache, you can use a set of functions to do the service.

    Unlike using EurekaClient class that you need to start and stop the client object by yourself, this method 
    will start the client automatically after the object created.

    read EurekaClient for more information for the parameters details.
    """
    ...

def get_client() -> EurekaClient:
    ...

async def walk_nodes_async(app_name: str = ..., service: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., walker: Callable = ...) -> Union[str, Dict, http_client.HttpResponse]:
    ...

async def do_service_async(app_name: str = ..., service: str = ..., return_type: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., method: str = ..., headers: Dict[str, str] = ..., data: Union[bytes, str, Dict] = ..., timeout: float = ...) -> Union[str, Dict, http_client.HttpResponse]:
    ...

async def stop_async() -> None:
    ...

_thread_local = ...
def set_event_loop(event_loop: asyncio.AbstractEventLoop): # -> None:
    ...

def get_event_loop() -> asyncio.AbstractEventLoop:
    ...

def init(eureka_server: str = ..., eureka_domain: str = ..., region: str = ..., zone: str = ..., eureka_availability_zones: Dict[str, str] = ..., eureka_protocol: str = ..., eureka_basic_auth_user: str = ..., eureka_basic_auth_password: str = ..., eureka_context: str = ..., prefer_same_zone: bool = ..., should_register: bool = ..., should_discover: bool = ..., on_error: Callable = ..., app_name: str = ..., instance_id: str = ..., instance_host: str = ..., instance_ip: str = ..., instance_ip_network: str = ..., instance_port: int = ..., instance_unsecure_port_enabled: bool = ..., instance_secure_port: int = ..., instance_secure_port_enabled: bool = ..., data_center_name: str = ..., renewal_interval_in_secs: int = ..., duration_in_secs: int = ..., home_page_url: str = ..., status_page_url: str = ..., health_check_url: str = ..., secure_health_check_url: str = ..., vip_adr: str = ..., secure_vip_addr: str = ..., is_coordinating_discovery_server: bool = ..., metadata: Dict = ..., remote_regions: List[str] = ..., ha_strategy: int = ..., strict_service_error_policy: bool = ...) -> EurekaClient:
    """
    Initialize an EurekaClient object and put it to cache, you can use a set of functions to do the service.

    Unlike using EurekaClient class that you need to start and stop the client object by yourself, this method 
    will start the client automatically after the object created.

    read EurekaClient for more information for the parameters details.
    """
    ...

def walk_nodes(app_name: str = ..., service: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., walker: Callable = ...) -> Union[str, Dict, http_client.HttpResponse]:
    ...

def do_service(app_name: str = ..., service: str = ..., return_type: str = ..., prefer_ip: bool = ..., prefer_https: bool = ..., method: str = ..., headers: Dict[str, str] = ..., data: Union[bytes, str, Dict] = ..., timeout: float = ...) -> Union[str, Dict, http_client.HttpResponse]:
    ...

def stop() -> None:
    ...

