"""
This type stub file was generated by pyright.
"""

from typing import List

"""
Copyright (c) 2018 Keijack Wu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
_logger = ...
class LeaseInfo:
    def __init__(self, renewalIntervalInSecs: int = ..., durationInSecs: int = ..., registrationTimestamp: int = ..., lastRenewalTimestamp: int = ..., renewalTimestamp: int = ..., evictionTimestamp: int = ..., serviceUpTimestamp: int = ...) -> None:
        ...
    


class DataCenterInfo:
    def __init__(self, name=..., className=..., metadata=...) -> None:
        ...
    


class PortWrapper:
    def __init__(self, port=..., enabled=...) -> None:
        ...
    


class Instance:
    def __init__(self, instanceId=..., sid=..., app=..., appGroupName=..., ipAddr=..., port=..., securePort=..., homePageUrl=..., statusPageUrl=..., healthCheckUrl=..., secureHealthCheckUrl=..., vipAddress=..., secureVipAddress=..., countryId=..., dataCenterInfo=..., hostName=..., status=..., overriddenstatus=..., leaseInfo=..., isCoordinatingDiscoveryServer=..., metadata=..., lastUpdatedTimestamp=..., lastDirtyTimestamp=..., actionType=..., asgName=...) -> None:
        ...
    
    @property
    def instanceId(self): # -> str:
        ...
    
    @instanceId.setter
    def instanceId(self, id): # -> None:
        ...
    
    @property
    def zone(self) -> str:
        ...
    


class Application:
    def __init__(self, name=..., instances=...) -> None:
        ...
    
    @property
    def instances(self) -> List[Instance]:
        ...
    
    @property
    def up_instances(self) -> List[Instance]:
        ...
    
    def get_instance(self, instance_id: str) -> Instance:
        ...
    
    def add_instance(self, instance: Instance) -> None:
        ...
    
    def update_instance(self, instance: Instance) -> None:
        ...
    
    def remove_instance(self, instance: Instance) -> None:
        ...
    
    def up_instances_in_zone(self, zone: str) -> List[Instance]:
        ...
    
    def up_instances_not_in_zone(self, zone: str) -> List[Instance]:
        ...
    


class Applications:
    def __init__(self, apps__hashcode=..., versions__delta=..., applications=...) -> None:
        ...
    
    @property
    def appsHashcode(self) -> str:
        ...
    
    @property
    def applications(self) -> List[Application]:
        ...
    
    @property
    def versionsDelta(self) -> str:
        ...
    
    def add_application(self, application: Application) -> None:
        ...
    
    def get_application(self, app_name: str = ...) -> Application:
        ...
    


async def register(eureka_server: str, instance: Instance) -> None:
    ...

async def cancel(eureka_server: str, app_name: str, instance_id: str) -> None:
    ...

async def send_heartbeat(eureka_server: str, app_name: str, instance_id: str, last_dirty_timestamp: int, status: str = ..., overriddenstatus: str = ...) -> None:
    ...

async def status_update(eureka_server: str, app_name: str, instance_id: str, last_dirty_timestamp, status: str = ..., overriddenstatus: str = ...): # -> None:
    ...

async def delete_status_override(eureka_server: str, app_name: str, instance_id: str, last_dirty_timestamp: str): # -> None:
    ...

async def get_applications(eureka_server: str, regions: List[str] = ...) -> Applications:
    ...

async def get_delta(eureka_server: str, regions: List[str] = ...) -> Applications:
    ...

async def get_vip(eureka_server: str, vip: str, regions: List[str] = ...) -> Applications:
    ...

async def get_secure_vip(eureka_server: str, svip: str, regions: List[str] = ...) -> Applications:
    ...

async def get_application(eureka_server: str, app_name: str) -> Application:
    ...

async def get_app_instance(eureka_server: str, app_name: str, instance_id: str) -> Instance:
    ...

async def get_instance(eureka_server: str, instance_id: str) -> Instance:
    ...

