"""
This type stub file was generated by pyright.
"""

from typing import Union

"""
Copyright (c) 2018 Keijack Wu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
_URL_REGEX = ...
class URLObj:
    def __init__(self, url: str = ..., basic_auth: str = ..., schema: str = ..., host: str = ..., ipv6: str = ..., port: int = ...) -> None:
        ...
    


def parse_url(url) -> URLObj:
    ...

class HttpRequest:
    def __init__(self, url, headers=..., method=...) -> None:
        ...
    
    def add_header(self, key: str, value: str): # -> None:
        ...
    


class HttpResponse:
    def __init__(self, raw_response=...) -> None:
        ...
    
    @property
    def body_text(self) -> str:
        ...
    
    @body_text.setter
    def body_text(self, value) -> None:
        ...
    


class HttpClient:
    async def urlopen(self, request: Union[str, HttpRequest] = ..., data: bytes = ..., timeout: float = ...) -> HttpResponse:
        ...
    


http_client = ...
def set_http_client(client: HttpClient) -> None:
    ...

