"""
This type stub file was generated by pyright.
"""

import logging
from abc import abstractmethod
from typing import Dict, List, Tuple

"""
Copyright (c) 2018 Keijack Wu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
_custom_logger: logging.Logger = ...
def set_custom_logger(logger: logging.Logger) -> None:
    ...

class LazyCalledLogger(logging.Logger):
    def do_call_handlers(self, record): # -> None:
        ...
    
    @abstractmethod
    def callHandlers(self, record): # -> None:
        ...
    


class LazyCalledLoggerThread:
    daemon_threads = ...
    def __init__(self) -> None:
        ...
    
    def coroutine_main(self): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def call_logger_handler(self, logger: LazyCalledLogger, record): # -> None:
        ...
    


class CachingLogger(LazyCalledLogger):
    logger_thread: LazyCalledLoggerThread = ...
    def callHandlers(self, record): # -> None:
        ...
    


class LoggerFactory:
    DEFAULT_LOG_FORMAT: str = ...
    DEFAULT_DATE_FORMAT: str = ...
    _LOG_LVELS: Tuple[str] = ...
    def __init__(self, log_level: str = ..., log_format: str = ..., date_format: str = ...) -> None:
        ...
    
    @property
    def handlers(self) -> List[logging.Handler]:
        ...
    
    @property
    def log_level(self): # -> str:
        ...
    
    @log_level.setter
    def log_level(self, log_level: str): # -> None:
        ...
    
    def add_handler(self, handler: logging.Handler) -> None:
        ...
    
    def remove_handler(self, handler: logging.Handler) -> None:
        ...
    
    def set_handler(self, handler: logging.Handler) -> None:
        ...
    
    def get_logger(self, tag: str = ...) -> logging.Logger:
        ...
    


_default_logger_factory: LoggerFactory = ...
_logger_factories: Dict[str, LoggerFactory] = ...
def get_logger_factory(tag: str = ...) -> LoggerFactory:
    ...

def set_level(level) -> None:
    ...

def add_handler(handler: logging.Handler) -> None:
    ...

def remove_handler(handler: logging.Handler) -> None:
    ...

def set_handler(handler: logging.Handler) -> None:
    ...

def get_logger(tag: str = ...) -> logging.Logger:
    ...

